### PR TITLE
Locations

### PR DESCRIPTION
**Pull request by mswider**
## Changes:

- Add text to action page to let people know about the availability of different locations in the school
image

## Todo:
- [x] Update availability on an interval
- Self-host availability data (no fetching from apps script)
    - [x] Make apps script trigger on spreadsheet 
    - [x] Create webhook
    - [x] Make apps script push data to webhook (on edit + reset)
    - [x] Make extension fetch from our server
- [x] Consider instances support

### CODE REVIEW

**Comment by mswider** [comment]
@edcous Any thoughts on how often we should update this?
It obviously loads when you open it, but if they keep it open should we refresh it every minute, 5 minutes, more?

**Comment by edcous** [comment]
> @edcous Any thoughts on how often we should update this?
> It obviously loads when you open it, but if they keep it open should we refresh it every minute, 5 minutes, more?

If it's a >1kb file in an S3 bucket that is on the same network, I see no reason that we wouldn't check every minute.

**Comment by edcous** [comment]
Do we want to make this only show up when the instance is set to the main campus?

**Review by edcous — COMMENTED** [review]
Do we want to make this only show up when the instance is set to the main campus?

**Comment by mswider** [comment]
> Do we want to make this only show up when the instance is set to the main campus?

Done

**Review by edcous — APPROVED** [review]

**Pull request merged**
